-- This file is autogenerated by the Rail schema generator, using
-- the schema defined in db/migration/*.rb
--
-- Do not edit this file.  Instead, add a new migration using
-- ./script/generate migration <name>, and then run
-- ./script/generate schema

-- tables 

CREATE TABLE articles (
  id int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  title varchar(255),
  author varchar(255),
  body text,
  body_html text,
  extended text,
  excerpt text,
  keywords varchar(255),
  allow_comments int(11),
  allow_pings int(11),
  published int(11) DEFAULT '1',
  created_at datetime,
  updated_at datetime,
  extended_html text,
  guid varchar(255),
  permalink varchar(255),
  user_id int(11),
  text_filter_id int(11)
) ENGINE=MyISAM;

CREATE TABLE articles_categories (
  article_id int(11),
  category_id int(11),
  is_primary int(11)
) ENGINE=MyISAM;

CREATE TABLE articles_tags (
  article_id int(11),
  tag_id int(11)
) ENGINE=MyISAM;

CREATE TABLE blacklist_patterns (
  id int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  type varchar(255),
  pattern varchar(255)
) ENGINE=MyISAM;

CREATE TABLE categories (
  id int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  name varchar(255),
  position int(11),
  permalink varchar(255)
) ENGINE=MyISAM;

CREATE TABLE comments (
  id int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  article_id int(11),
  title varchar(255),
  author varchar(255),
  email varchar(255),
  url varchar(255),
  ip varchar(255),
  body text,
  body_html text,
  created_at datetime,
  updated_at datetime,
  user_id int(11),
  guid varchar(255)
) ENGINE=MyISAM;

CREATE TABLE page_caches (
  id int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  name varchar(255)
) ENGINE=MyISAM;

CREATE TABLE pages (
  id int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  name varchar(255),
  user_id int(11),
  body text,
  body_html text,
  created_at datetime,
  updated_at datetime,
  title varchar(255),
  text_filter_id int(11)
) ENGINE=MyISAM;

CREATE TABLE pings (
  id int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  article_id int(11),
  url varchar(255),
  created_at datetime
) ENGINE=MyISAM;

CREATE TABLE resources (
  id int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  size int(11),
  filename varchar(255),
  mime varchar(255),
  created_at datetime,
  updated_at datetime,
  article_id int(11)
) ENGINE=MyISAM;

CREATE TABLE sessions (
  id int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  sessid varchar(255),
  data text,
  created_at datetime,
  updated_at datetime
) ENGINE=MyISAM;

CREATE TABLE settings (
  id int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  name varchar(255),
  value varchar(255),
  position int(11)
) ENGINE=MyISAM;

CREATE TABLE sidebars (
  id int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  controller varchar(255),
  active_position int(11),
  active_config text,
  staged_position int(11),
  staged_config text
) ENGINE=MyISAM;

CREATE TABLE tags (
  id int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  name varchar(255),
  created_at datetime,
  updated_at datetime
) ENGINE=MyISAM;

CREATE TABLE text_filters (
  id int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  name varchar(255),
  description varchar(255),
  markup varchar(255),
  filters text,
  params text
) ENGINE=MyISAM;

CREATE TABLE trackbacks (
  id int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  article_id int(11),
  blog_name varchar(255),
  title varchar(255),
  excerpt varchar(255),
  url varchar(255),
  ip varchar(255),
  created_at datetime,
  updated_at datetime,
  guid varchar(255)
) ENGINE=MyISAM;

CREATE TABLE users (
  id int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  login varchar(255),
  password varchar(255),
  email text,
  name text
) ENGINE=MyISAM;


-- indexes 

CREATE  INDEX articles_permalink_index ON articles (permalink);
CREATE  INDEX blacklist_patterns_pattern_index ON blacklist_patterns (pattern);
CREATE  INDEX categories_permalink_index ON categories (permalink);
CREATE  INDEX comments_article_id_index ON comments (article_id);
CREATE  INDEX page_caches_name_index ON page_caches (name);
CREATE  INDEX pings_article_id_index ON pings (article_id);
CREATE  INDEX trackbacks_article_id_index ON trackbacks (article_id);

-- data 

INSERT INTO sidebars (`staged_position`, `active_config`, `active_position`, `controller`, `staged_config`) VALUES(NULL, NULL, 0, 'category', NULL);
INSERT INTO sidebars (`staged_position`, `active_config`, `active_position`, `controller`, `staged_config`) VALUES(NULL, NULL, 1, 'static', NULL);
INSERT INTO sidebars (`staged_position`, `active_config`, `active_position`, `controller`, `staged_config`) VALUES(NULL, NULL, 2, 'xml', NULL);
INSERT INTO text_filters (`name`, `filters`, `description`, `params`, `markup`) VALUES('none', '--- []', 'None', '--- {}', 'none');
INSERT INTO text_filters (`name`, `filters`, `description`, `params`, `markup`) VALUES('markdown', '--- []', 'Markdown', '--- {}', 'markdown');
INSERT INTO text_filters (`name`, `filters`, `description`, `params`, `markup`) VALUES('smartypants', '--- 
- :smartypants', 'SmartyPants', '--- {}', 'none');
INSERT INTO text_filters (`name`, `filters`, `description`, `params`, `markup`) VALUES('markdown smartypants', '--- 
- :smartypants', 'Markdown with SmartyPants', '--- {}', 'markdown');
INSERT INTO text_filters (`name`, `filters`, `description`, `params`, `markup`) VALUES('textile', '--- []', 'Textile', '--- {}', 'textile');

-- schema version meta-info 

CREATE TABLE schema_info (
  version int(11)
) ENGINE=MyISAM;

insert into schema_info (version) values (18);
